remote_theme: pages-themes/free-magneto2-theme
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Emily Bower
# description: Showcase my academic journey
